### ISSUE TITLE
Question: How to setup docker in awscodebuild

### ISSUE THREAD

**Issue by prashantrbs** [sumitbera/WebAppAutomation#12]
Hi Sumit,

I read you blog and its very clear to understand however i have a question, i saw your running tests on pipeLine and in docker. Where did you setup docker and docker-compose? in my local i have docker and docker compose installed but in aws i am not sure where to install and which remote URL to provide. Can you please help me with this?

Thanks,
Prashant

**Comment by sumitbera** [comment]
Hi Prashant, if you are using AWS CodePipeline then refer the **Build Environment** screenshot. AWS runs the codepipeline in pre-installed docker environment. So you will have the docker already available you simply need to pass the buildspec.yml file and rest will be taken care in the pipeline. Feel free to reach out if you face any issues while running it. Also you don't need to worry about remoteUrl, the docker compose when bring up a selenium grid in the pipeline, it will refer the localhost from that machine

**Comment by prashantrbs** [comment]
Thanks for reply Sumit. yes I see **Build Environment** screenshot i saw you have the docker option but i didn't have that. do you know why is like that?
![image](https://user-images.githubusercontent.com/44323121/220588649-4370bf38-32ca-4a4b-be55-2538a543ea8e.png)

**Comment by sumitbera** [comment]
Hi Prashant

While creating code pipeline, Under the Add build stage, Click on **Create Project**, which will open another window of **AWS CodeBuild** and you can see the environment section over there. See the screenshot.

![Screenshot 2023-02-22 at 9 19 33 PM](https://user-images.githubusercontent.com/12911549/220592522-772a8c96-cb98-4874-b31e-711994ac7a63.png)
![Screenshot 2023-02-22 at 9 24 10 PM](https://user-images.githubusercontent.com/12911549/220592916-0041a38d-1c2d-41b3-9790-ff8bb50ba549.png)

Let me know if it works for you

**Comment by prashantrbs** [comment]
Yes Sumit this will work i think but in codeBuild environment section doesn't have docker option. I will try this for sure.

Other question: i was checking a couple of other blogs they are using ec2 for creating instances for docker and docker-compose. How it is different from your approach? can you give some light on this? since I am new to aws i am not sure which option to use. sorry for keep bothering you.

**Comment by sumitbera** [comment]
You will have to pick Managed image option and pick Ubuntu, that will have docker already, Just to let you know AWS Codepipeline uses EC2 instances behind the picture to run CI pipelines based on the specification you pass while creating the pipeline. So that's the answer to your second question.

If you use EC2 instance you have to install both docker and docker compose in the EC2, and you might want to keep the machine running (incur charges) or start/stop based on your demand. Whereas in code pipeline all the infrastructure used behind the scene is on demand so you pay only for that.

If you are using docker you can explore other options like Bitbucket pipelines or Github actions they both take same spec file and comes with docker support.

**Comment by prashantrbs** [comment]
Awesome Sumit that answers my question. Yes, i tried gitHub action but due to high charges we stop using it.

Thanks for your valuable time.
